### ISSUE TITLE
Lack of cpu_set_t on macOS

### ISSUE THREAD

**Issue by maedoc** [celerity/celerity-runtime#85]
macOS appears to lack cpu_set_t, though it seems the use is rather limited to counting cores, so some other API could stand in on macOS, e.g. [here](https://stackoverflow.com/a/5143867).

**Comment by maedoc** [comment]
Otherwise by commenting out those core count usages I was able to build from source.

**Comment by psalz** [comment]
Thanks for bringing this to our attention. While we don't "officially" support macOS (we neither have CI set up nor am I aware of anyone in our team having a Mac), I think we can certainly work around minor issues such as this. That being said, I'm not sure how important it would be to have that warning on macOS in the first place, as I would expect Macs to mostly be used during development (same as Windows, really). So we could just conditionally disable it. Unless you want to file a PR, of course :-).

I'm also interested in those test failures. What SYCL implementation and version are you building against?

**Comment by maedoc** [comment]
> Macs to mostly be used during development 

That's my case, and I will likely switch to Docker in order to test multi "node" (i.e. containers) scenarios, where this issue doesn't arise.

> What SYCL implementation and version are you building against?

hipSYCL, develop branch at 209a7aac3ec, with the OMP backend.  But it could have as much to do with the hacks to get celerity to build, right? 
```diff
index 7d1d245..8aa311d 100644
--- a/src/platform_specific/affinity.unix.cc
+++ b/src/platform_specific/affinity.unix.cc
@@ -5,17 +5,20 @@
 #include <pthread.h>
 #include <sched.h>

-#include "affinity.h"
+// #include "affinity.h"

 namespace celerity {
 namespace detail {

        uint32_t affinity_cores_available() {
+               return 4;
+               /*
                cpu_set_t available_cores;
                const auto affinity_error = pthread_getaffinity_np(pthread_self(), sizeof(cpu_set_t), &available_cores);
                assert(affinity_error == 0 && "Error retrieving affinity mask.");
                return CPU_COUNT(&available_cores);
+               */
        }

 } // namespace detail
-} // namespace celerity
\ No newline at end of file
+} // namespace celerity
diff --git a/test/runtime_tests.cc b/test/runtime_tests.cc
index 4051b76..c914f99 100644
--- a/test/runtime_tests.cc
+++ b/test/runtime_tests.cc
@@ -15,7 +15,7 @@

 #include <celerity.h>

-#include "affinity.h"
+// #include "affinity.h"
 #include "ranges.h"
 #include "region_map.h"

@@ -2321,13 +2321,15 @@ namespace detail {
                }
 #else
                SECTION("in Posix") {
+                       /*
                        cpu_set_t cpu_mask;
                        CPU_ZERO(&cpu_mask);
                        CPU_SET(0, &cpu_mask);
                        pthread_setaffinity_np(pthread_self(), sizeof(cpu_mask), &cpu_mask);
+                       */
                }
 #endif
-               const auto cores = affinity_cores_available();
+               const auto cores = 1;//affinity_cores_available();
                REQUIRE(cores == 1);
        }
```

**Comment by psalz** [comment]
> hipSYCL, develop branch at 209a7aac3ec, with the OMP backend. But it could have as much to do with the hacks to get celerity to build, right?

Hmm, I don't think so. What's weird is that those tests shouldn't even be enabled as [hipSYCL doesn't support reductions](https://github.com/celerity/celerity-runtime/blob/113e68802ca0b114ed2aac6bae71052a2b7a5d36/CMakeLists.txt#L121) without [a patch](https://github.com/illuhad/hipSYCL/pull/578). Could you tell me what CMake says during configuration? Does it print `"hipSYCL supports SYCL 2020 reductions"`?

**Comment by maedoc** [comment]
> Does it print "hipSYCL supports SYCL 2020 reductions"?

Nope:

```
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_CXX: /usr/local/Cellar/open-mpi/4.1.1_2/lib/libmpi.dylib (found suitable version "3.1", minimum required is "2.0")
-- Found MPI: TRUE (found suitable version "3.1", minimum required is "2.0")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found hipSYCL: /usr/local/lib/cmake/hipSYCL
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenCL.framework (found version "1.2")
-- Automatically chooosing hipSYCL because it is the only SYCL implementation available
-- hipSYCL does NOT support SYCL 2020 reductions
-- Build spdlog: 1.4.0
-- Build type: Release
-- Checking for one of the modules 'hdf5-openmpi;hdf5-1.12.0;hdf5'
-- Configuring done
```
For the record, I'm on master at 113e68802

**Comment by almightyvats** [comment]
The reduction tests in `runtime_test` are disabled for me. `macOS Monterey Version 12.1`

**Comment by PeterTh** [comment]
Then I think we can resolve this issue (since the original problem is solved and the strange behavior regarding the unit tests can't currently be reproduced).
